# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
# "server.js" = "selected"
# "run.sh" = "selected"
# "package.json" = "selected"
# "frontend/package-lock.json" = "selected"
# "frontend/package.json" = "selected"
# "frontend/public/index.html" = "selected"
# "frontend/build/index.html" = "selected"
# "frontend/build/asset-manifest.json" = "selected"
# "frontend/build/static/js/2.f7b0c6c1.chunk.js.LICENSE.txt" = "selected"
# "frontend/build/static/js/2.f7b0c6c1.chunk.js.map" = "selected"
# "frontend/build/static/js/runtime-main.3e714a9c.js.map" = "selected"
# "frontend/build/static/js/runtime-main.3e714a9c.js" = "selected"
# "frontend/build/static/js/main.2212da3c.chunk.js" = "selected"
# "frontend/build/static/js/2.f7b0c6c1.chunk.js" = "selected"
# "frontend/build/static/js/main.2212da3c.chunk.js.map" = "selected"
"frontend/src/index.js" = "selected"
# "frontend/src/index.css" = "selected"
"frontend/src/App.js" = "selected"
# "frontend/src/components/Taskbar.css" = "selected"
# "frontend/src/components/Taskbar.js" = "selected"
# "frontend/src/components/App.css" = "selected"
# "frontend/src/components/ProductList.js" = "selected"
# "frontend/src/components/AddProduct.js" = "selected"
# "backend/db.sqlite" = "selected"
# "backend/package-lock.json" = "selected"
# "backend/package.json" = "selected"
# "backend/src/app.js" = "selected"
# "backend/src/models/db.js" = "selected"
# "backend/src/models/productModel.js" = "selected"
# "backend/src/controllers/productController.js" = "selected"
# "backend/src/routes/productRoutes.js" = "selected"
# 